name: Publish to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v1

      - name: Setup Yarn
        run: yarn

      - name: Build
        run: yarn build

      - name: Disable Jekyll
        run: "touch dist/.nojekyll"

      - name: "Add Webmanifest"
        run: "cp manifest.webmanifest dist/manifest.webmanifest"

      - name: "Add CNAME File"
        run: "cp CNAME dist/CNAME"

      - name: Publish generated content to GitHub Pages
        uses: tsunematsu21/actions-publish-gh-pages@v1.0.2
        with:
          dir: dist
          branch: gh-pages
          token: ${{ secrets.ACCESS_TOKEN }}
